-- REVOKE ALL PRIVILEGES ON *.* FROM 'public'@'%'; 
-- REVOKE GRANT OPTION ON *.* FROM 'public'@'%'; 
GRANT SELECT, INSERT, UPDATE, DELETE, FILE ON *.* TO 'public'@'%' REQUIRE NONE WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0; 